---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: moviefun-pks-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: thin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi