---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviefun-pks-msg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moviefun-pks-msg
  template:
    metadata:
      labels:
        app: moviefun-pks-msg
    spec:
      containers:
        - name: moviefun-pks-msg
          image: pivotaleducation/moviefun-pks:2.0
          envFrom:
            - secretRef:
                name: moviefun-pks-secret-msg
          ports:
            - containerPort: 8080
          volumeMounts:
          - mountPath: "/var/albumCovers"
            name: some-disk
      volumes:
        - name: some-disk
          persistentVolumeClaim:
            claimName: moviefun-claim