---
apiVersion: v1
kind: Service
metadata:
  name: moviefun-pks-bcd-lb
spec:
  selector:
    app: moviefun-pks-bcd
  type: NodePort
  ports:
    - port: 80
      nodePort: 30819
      targetPort: 8080
      protocol: TCP
      name: http
