---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviefun-pks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moviefun-pks
  template:
    metadata:
      labels:
        app: moviefun-pks
    spec:
      containers:
      - name: moviefun-pks
        image: pivotaleducation/moviefun-pks:2.0
        imagePullPolicy: Always
        env:
        - name: SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS
          value: "true"
        - name: MOVIEFUN_TITLE
          value: "MyMovieFun"
        ports:
        - containerPort: 8080
