---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviefun-pks-bcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moviefun-pks-bcd
  template:
    metadata:
      labels:
        app: moviefun-pks-bcd
    spec:
      containers:
      - name: moviefun-pks-bcd
        image: pivotaleducation/moviefun-pks:1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: JPDA_ADDRESS
          value: "5005"
        ports:
        - containerPort: 5005
        - containerPort: 8080

