---
apiVersion: v1
kind: Service
metadata:
  name: moviefun-pks-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: moviefun-pks
    version: v2.0
  type: LoadBalancer
