---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: moviefun-pks-v3
  labels:
    app: moviefun-pks
    version: v3.0
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: moviefun-pks-v3
  targetCPUUtilizationPercentage: 80
