apiVersion: v1
kind: PersistentVolume
metadata:
  name: moviefun-pks-local-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: moviefun-pks-local-storage
  local:
    path: /mnt/disk/moviefun
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 1e00801a-4a51-4672-9aa6-943df1b23043
